# Generated by Django 3.0.5 on 2021-01-04 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quotesapp', '0002_quotes_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quotes',
            old_name='author',
            new_name='by',
        ),
    ]
